### ISSUE TITLE
Release macOS version

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#37]
Optionally get it released on the App Store for macs

**Comment by SikhNerd** [comment]
Even if you don't use it, notes here will be helpful when prepping to release to MAS: https://github.com/electron-userland/electron-osx-sign

**Comment by bhajneet** [comment]
Definitely -- thank you!

**Comment by Harjot1Singh** [comment]
Issue with notarization:

```
** Error: Unable to validate your application. We are unable to create an authentication session.

    at /Users/distiller/shabad-os/node_modules/electron-notarize/src/index.ts:82:13
    at step (/Users/distiller/shabad-os/node_modules/electron-notarize/lib/index.js:31:23)
    at Object.next (/Users/distiller/shabad-os/node_modules/electron-notarize/lib/index.js:12:53)
    at fulfilled (/Users/distiller/shabad-os/node_modules/electron-notarize/lib/index.js:3:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Done notarizing com.shabados.desktop
```
